import SwiftUI
import AVKit

final class DContr: NSObject, AVAudioPlayerDelegate {
    
    let cdm = CDM()
    @AppStorage("lastWordForEveryone") var lastWordForEveryone = true
    @AppStorage("superWord") var superWord = true
    
    var commands: Array<Command> = []
    var currentPlayer: Command?
    var wordForNextRound: Word?
    
    var gameWords: Array<Word> = []
    var answeredWords: Array<(Word, Bool)> = []
    
    var complexity: Complexity = .medium
    var numberOfPointsToWin: Int = 25
    var roundTime = 30
    var takeAwayPoints = false
    
    var player: AVAudioPlayer?
    var playerAnswer: AVAudioPlayer?
    
    override init() {
        super.init()
        setMusic()
    }
    
    func load() {
        if let commands = try? cdm.fetchScore() {
            commands.forEach { si in
                var element = availableCommands.first(where: {$0.title == si.0})
                if element != nil {
                    availableCommands.remove(element!)
                    element?.totalScore += si.1
                    availableCommands.insert(element!)
                }
            }
        }
    }
    
    func setMusic() {
        guard let path = Bundle.main.path(forResource: "Main", ofType: "mp3") else {
            return }
        let url = URL(fileURLWithPath: path)
        do {
            player = try AVAudioPlayer(contentsOf: url)
            player?.delegate = self
            player?.currentTime = 0
            player?.volume = 0.4
            player?.play()
            
        } catch let error {
            print(error.localizedDescription)
        }
    }
    
    func setAnswerSound(_ isRight: Bool) {
        guard let path = Bundle.main.path(forResource: isRight ? "Right" : "Wrong", ofType: "mp3") else {
            return }
        let url = URL(fileURLWithPath: path)
        do {
            playerAnswer = try AVAudioPlayer(contentsOf: url)
            playerAnswer?.delegate = self
            playerAnswer?.currentTime = 0
            playerAnswer?.play()
            
        } catch let error {
            print(error.localizedDescription)
        }
    }
    
    func saveScore(_ commands: [Command]) {
        for i in 0..<commands.count {
            var element = availableCommands.first(where: {$0.title == commands[i].title})
            if element != nil {
                availableCommands.remove(element!)
                element?.totalScore += commands[i].score
                availableCommands.insert(element!)
            }
        }
        cdm.saveOrEditScore(availableCommands)
    }
    
    var categories: Array<Category> = [
        Category(title: "Sport", image: "Sport", selected: false, wordsId: 0),
        Category(title: "Cartoons", image: "Cartoons", selected: false, wordsId: 1),
        Category(title: "Animals", image: "Animals", selected: false, wordsId: 2),
        Category(title: "Harry Potter", image: "HarryPotter", selected: false, wordsId: 3),
        Category(title: "Gaming", image: "Gaming", selected: false, wordsId: 4),
        Category(title: "Celebrities", image: "Celebrities", selected: false, wordsId: 5),
        Category(title: "Food", image: "Food", selected: false, wordsId: 6),
        Category(title: "Nature", image: "Nature", selected: false, wordsId: 7),
        Category(title: "Transportation", image: "Transportation", selected: false, wordsId: 8),
        Category(title: "All categories", image: "AllCategories", selected: false, wordsId: 9)
    ]
    
    var availableCommands: Set<Command> = [
        Command(title: "Cheese Ninjas", image: "CheeseNinjas", score: 0, totalScore: 0),
        Command(title: "Luck Cupcakes", image: "LuckCupcakes", score: 0, totalScore: 0),
        Command(title: "Space Beavers", image: "SpaceBeavers", score: 0, totalScore: 0),
        Command(title: "BBQ Knights", image: "BBQKnights", score: 0, totalScore: 0),
        Command(title: "Cucumber Yogis", image: "CucumberYogis", score: 0, totalScore: 0),
        Command(title: "Banana Samurai", image: "BananaSamurai", score: 0, totalScore: 0),
        Command(title: "Wind Hamsters", image: "WindHamsters", score: 0, totalScore: 0),
        Command(title: "Caramel Pirates", image: "CaramelPirates", score: 0, totalScore: 0),
        Command(title: "Hedgehogs in Sneakers", image: "HedgehogsinSneakers", score: 0, totalScore: 0)
    ]
    
    var words: Array<Words> = [
        Words(id: 0, 
              easy: 
                [
                "Soccer",
                "Basketball",
                "Volleyball",
                "Tennis",
                "Hockey",
                "Rugby",
                "Boxing",
                "Swimming",
                "Athletics",
                "Fencing",
                "Gymnastics",
                "Skateboarding",
                "Snowboarding",
                "Alpine skiing",
                "Parachuting",
                "Cycling",
                "Triathlon",
                "Karate",
                "Judo",
                "Taekwondo",
                "Wrestling",
                "Chess",
                "Billiards",
                "Darts",
                "Table tennis",
                "Sumo",
                "Cybersports",
                "Aerobics",
                "Yoga",
                "Fitness",
                "Crossfit",
                "Pilates",
                "Squash",
                "Running",
                "Walking",
                "Sport Walking",
                "Gym",
                "Rowing",
                "Fun Riding",
                "Rock Climbing",
                "Surfing",
                "Kitesurfing",
                "Roller skating",
                "Mountaineering",
                "Dancing"
                           ],
                     medium: [
                        "Breakdance",
                        "Modern dance",
                        "Ballet",
                        "Choreography",
                        "Futsal",
                        "Beach volleyball",
                        "Golf",
                        "Motor sports",
                        "Motorcycling",
                        "Karting",
                        "Water Polo",
                        "Rugby Sevens",
                        "Freestyle",
                        "Judo",
                        "Karate",
                        "Kettlebell lifting",
                        "Paragliding",
                        "Canoeing",
                        "Karting",
                        "Windsurfing",
                        "Short track",
                        "Figure skating",
                        "Speed Skating",
                        "Gymnastics",
                        "Rowing",
                        "High jumping",
                        "Skydiving",
                        "Ski jumping",
                        "Weightlifting",
                        "Long Jump",
                        "Javelin",
                        "Discus throw",
                        "Tennis ball",
                        "Soccer ball",
                        "Volleyball",
                        "Basketball",
                        "Skis",
                        "Snowboard",
                        "Sneakers",
                        "Treadmills",
                        "Exercise equipment",
                        "Equipment",
                        "Exercise",
                        "Stretching"
                     ],
                     hard: [
                        "Cardio workout",
                        "Strength training",
                        "Functional training",
                        "Competitions",
                        "Tournament",
                        "Championship",
                        "League",
                        "Cup",
                        "Medal",
                        "Prize",
                        "Diploma",
                        "Coach",
                        "Athlete",
                        "Team",
                        "Composition",
                        "Ground",
                        "Swimming pool",
                        "Ice arena",
                        "Sports hall",
                        "Training",
                        "Warm-up",
                        "Result",
                        "Record",
                        "Strategy",
                        "Tactics",
                        "Technique",
                        "Level",
                        "Rewarding",
                        "Charity match"
                     ]),
        Words(id: 1, 
              easy: [
            "Cartoon",
            "Cat",
            "Puppy",
            "Friendship",
            "Fairy tale",
            "Wizard",
            "Princess",
            "Villain",
            "Hero",
            "Dragon",
            "Castle",
            "Forest",
            "Park",
            "Magic",
            "Flying carpet",
            "Unicorn",
            "Robot",
            "Airplane",
            "Space",
            "Star",
            "Bird",
            "Fish",
            "Tree",
            "Sea",
            "Island",
            "School",
            "Book",
            "Mission",
            "Secret",
            "Map",
            "Labyrinth",
            "Thief",
            "City",
            "Home",
            "Sunny Day",
            "Rocket",
            "Journey",
            "Pirate",
            "Ship",
            "Treasure",
            "Friends",
            "Guide",
            "Rescue",
            "Train",
            "Butterfly",
            "Morning",
            "Winter",
            "Summer",
            "Car",
            "Bicycle",
            "Ocean",
            "Moon",
            "Smile"
         ],
         medium: [
            "Cartoon",
            "Hero",
            "Character",
            "Series",
            "Episode",
            "Story",
            "Story",
            "Dubbing",
            "Voiceover",
            "Animation",
            "Graphics",
            "Script",
            "Special Effects",
            "Director",
            "Artist",
            "Producer",
            "Location",
            "Antagonist",
            "Protagonist",
            "Foreshortening",
            "Scene",
            "Plan",
            "Camera",
            "Montage",
            "Dynamics",
            "Dialogue",
            "Frame",
            "Studio",
            "Screensaver",
            "Finale",
            "Landscape",
            "Operator",
            "Scenery",
            "Voiceover",
            "Background",
            "Titles",
            "Protagonist",
            "Villain",
            "Music",
            "Background animation",
            "Spin-off",
            "Animation",
            "Video montage",
            "Remake",
            "Art style",
            "Trailer",
            "Cinematography",
            "Fantasy",
            "Adventure",
            "Heroic",
            "Transformation",
            "Magic",
            "Pilot"
         ],
         hard: [
            "Animation",
            "Rotoscopy",
            "Anthropomorphism",
            "Polyscreen",
            "Metamorphosis",
            "Pixelization",
            "Compositing",
            "Photorealism",
            "Story arc",
            "Protagonist",
            "Antagonist",
            "Lipsync",
            "Decoding",
            "Characterization",
            "Chronology",
            "Animatics",
            "Stop-motion",
            "Branding",
            "Crossover",
            "Hyperbolization",
            "Phoneme synchronization",
            "Cartoon",
            "Sketch animation",
            "Grotesque",
            "Symbolism",
            "Colorism",
            "Contrajour",
            "Key pose",
            "Parallax",
            "Background animation",
            "Avant-garde animation",
            "Reshaping",
            "Montage splicing",
            "Temporal",
            "Transition scene",
            "Pre-production",
            "Post-production",
            "Dubbing",
            "Character Design",
            "Philosophical Undertones",
            "Line editing",
            "Tracing",
            "Vector graphics",
            "Movie effect",
            "Virtual camera",
            "Frame",
            "Phantom Lines",
            "Mocap",
            "Non-linear narration",
            "Frame fluidity",
            "Conflict initiation",
            "Flash animation",
            "Parallelism"
         ]),
        Words(id: 2, 
              easy: [
            "Lion",
            "Tiger",
            "Zebra",
            "Penguin",
            "Giraffe",
            "Elephant",
            "Cheetah",
            "Koala",
            "Panda",
            "Kangaroo",
            "Rhinoceros",
            "Leopard",
            "Monkey",
            "Jaguar",
            "Camel",
            "Crocodile",
            "Hippopotamus",
            "Jackal",
            "Lemur",
            "Chameleon",
            "Parrot",
            "Dolphin",
            "Shark",
            "Pelican",
            "Eagle",
            "Elk",
            "Boar",
            "Wolf",
            "Bear",
            "Badger",
            "Raccoon",
            "Lynx",
            "Meerkat",
            "Fox",
            "Swan",
            "Owl",
            "Turtle",
            "Ostrich",
            "Scat",
            "Antelope",
            "Skunk",
            "Coyote",
            "Buffalo",
            "Flamingo",
            "Iguana"
         ],
         medium: [
            "Cat",
            "Dog",
            "Cow",
            "Horse",
            "Chicken",
            "Duck",
            "Rooster",
            "Goat",
            "Sheep",
            "Fish",
            "Mouse",
            "Rabbit",
            "Pig",
            "Fox",
            "Hippo",
            "Bull",
            "Tiger",
            "Bear",
            "Wolf",
            "Toad",
            "Lion",
            "Penguin",
            "Hare",
            "Squirrel",
            "Hedgehog",
            "Frog",
            "Eagle",
            "Seagull",
            "Mole",
            "Goose",
            "Sparrow",
            "Peacock",
            "Turtle",
            "Stork",
            "Crow",
            "Giraffe",
            "Ant",
            "Bee",
            "Butterfly",
            "Dragonfly",
            "Spider",
            "Mosquito",
            "Snail",
            "Grasshopper",
            "snake"
         ],
         hard: [
            "Oryx",
            "Dugong",
            "Ocelot",
            "Aye-aye",
            "Narwhal",
            "Axolotl",
            "Capybara",
            "Quokka",
            "Binturong",
            "Wombat",
            "Gaur",
            "Kiwi (bird)",
            "Galago",
            "Kasuar",
            "Mongoose",
            "Tapir",
            "Koipu",
            "Paca",
            "Pakarana",
            "Kulan",
            "Fossa",
            "Wihuhol",
            "Tuatara",
            "Monkey",
            "Caracal",
            "Jairan",
            "Vizcacha",
            "Pangolin",
            "Echidna",
            "Harpy (bird)",
            "Cob",
            "Toucan",
            "Bustard",
            "Crax",
            "Civet",
            "Kakapo",
            "Flamingo",
            "Coati",
            "Marginalis",
            "Capuchin",
            "Candelabra (coral)",
            "Irbis",
            "Guanaco",
            "Saola",
            "Psittacosaurus"
         ]),
        Words(id: 3, 
              easy: [
            "Harry",
            "Potter",
            "Hermione",
            "Ron",
            "Hogwarts",
            "School",
            "Magic",
            "Wizardry",
            "Spell",
            "Book",
            "Tale",
            "Magician",
            "Spells",
            "Wand",
            "Potion",
            "Cauldron",
            "Dragon",
            "Gryffindor",
            "Slytherin",
            "Ravenclaw",
            "Puffendui",
            "Professor",
            "Headmaster",
            "Headmaster",
            "Map",
            "Cloak",
            "Hat",
            "Voldemort",
            "Lord",
            "Evil",
            "Good",
            "Boggart",
            "Portal",
            "Mr.",
            "Ms.",
            "Store",
            "Chocolate",
            "Balloon",
            "Cat",
            "Friends",
            "Phoenix",
            "Harpy",
            "Half-orc",
            "Creature",
            "Flying",
            "Carpet",
            "Forest",
            "Night",
            "Morning",
            "Spell",
            "Quill",
            "Money",
            "Thing",
            "Seal",
            "Key",
            "Child",
            "Flash drive",
            "Briefcase",
            "Suitcase",
            "Backpack",
            "Bed",
            "Table",
            "Book",
            "Light bulb",
            "Map",
            "Tree",
            "Moon",
            "Star",
            "Wing",
            "Suit",
            "Helmet",
            "Body",
            "Closet",
            "Academy",
            "Goblin",
            "Paperclip",
            "Map",
            "Whip",
            "Sound",
            "Secret"
         ],
         medium: [
            "Harry",
            "Potter",
            "Hermione",
            "Ron",
            "Hogwarts",
            "Voldemort",
            "Dumbledore",
            "Snape",
            "Slytherin",
            "Gryffindor",
            "Ravenclaw",
            "Puffendui",
            "Nicholas Flamel",
            "Hedwig",
            "Lord",
            "Serfs",
            "Map",
            "Magic",
            "Potion",
            "Wand",
            "Deathly Hallows",
            "Book",
            "Portal",
            "Phoenix",
            "Secrets",
            "Boggart",
            "Spell",
            "Curveballs",
            "Secret",
            "Hat",
            "Cobra",
            "Seal",
            "Marauder's Map",
            "Gringotts",
            "Magic Wands",
            "Lunatic",
            "Laurel Wreath",
            "Potions",
            "Witch",
            "Course",
            "Testing",
            "Tournament",
            "Stone",
            "Dungeon",
            "Happiness",
            "Collection",
            "Snapshot",
            "Spellbook",
            "Inquisitor",
            "Artifact",
            "Closet",
            "Enchantment",
            "Guards",
            "Course",
            "Crack",
            "Wolfman",
            "Golden Snitch",
            "Witcher",
            "Head",
            "Christmas",
            "Slippers",
            "Muggle",
            "Turning Point",
            "Filius Flitwick",
            "Slytherins",
            "Mode",
            "Wand",
            "Humanity",
            "Trips",
            "Troll",
            "Snowflakes",
            "School",
            "Briefcase",
            "Harpy",
            "Balloon",
            "Meeting",
            "Cloth",
            "Mr. Bureau",
            "Magic"
         ],
         hard: [
            "Harry Potter",
            "Hermione Granger",
            "Ron Weasley",
            "Albus Dumbledore",
            "Severus Snape",
            "Voldemort",
            "Remus Lupin",
            "Neville Longbourn",
            "Draco Malfoy",
            "Sirius Black",
            "Lily Potter",
            "James Potter",
            "Minerva McGonagall",
            "Filius Flitwick",
            "Rubeus Hagrid",
            "Rita Skeeter",
            "Gregory Goyle",
            "Vincent Crabbe",
            "Pettigrew",
            "Bellatrix Lestrange",
            "Narcissa Malfoy",
            "Lucius Malfoy",
            "Tom Riddle",
            "Roger Davies",
            "Dean Thomas",
            "Severus Snape",
            "Slaven Malfoy",
            "Parvati Patil",
            "Padma Patil",
            "Fred Weasley",
            "George Weasley",
            "Molly Weasley",
            "Arthur Weasley",
            "Charlie Weasley",
            "Percy Weasley",
            "Ginevra Weasley",
            "Luna Lovegood",
            "Xenophilius Lovegood",
            "Herbert Watch",
            "Cedric Diggory",
            "Ollivander",
            "Professor Sprout",
            "Professor Sinistra",
            "Professor Slackhorn",
            "Tonks",
            "Remus Lupin",
            "Mungo Bondi",
            "Kreacher",
            "Fenrir Greyback",
            "Harry Potter",
            "Godric Gryffindor",
            "Helga Hufflepuff",
            "Ravena Ravenclaw",
            "Salazar Slytherin",
            "Ginny Weasley",
            "Albus Potter",
            "James Potter II",
            "Lily Potter II",
            "Scorpius Malfoy",
            "Astoria Granger",
            "Fred Weasley II",
            "George Weasley II",
            "Neville Longbourn II",
            "Randall Slaper",
            "Nicholas Flamel",
            "Granger",
            "Quirrell",
            "George Longbortom",
            "Anne Longbortom",
            "Susanna Tonks",
            "Thomas Riddle",
            "William Powell",
            "Edward Seaton",
            "Barty Crouch",
            "Harry Potter",
            "Lorna James",
            "Amelia Bones",
            "Penelope",
            "Tom Riddle"
         ]),
        Words(id: 4, 
              easy: [
                 "Game console",
                 "Computer",
                 "Platform",
                 "Keyboard",
                 "Mouse",
                 "Monitor",
                 "Gamepad",
                 "Pixels",
                 "Graphics",
                 "Picture",
                 "Level",
                 "Mission",
                 "Task",
                 "Quest",
                 "Character",
                 "Mod",
                 "Achievement",
                 "Points",
                 "Saving",
                 "Loading",
                 "Game Menu",
                 "Settings",
                 "Story",
                 "Story",
                 "Game",
                 "Gameplay",
                 "Secrets",
                 "Secret Places",
                 "Bonus",
                 "Rating",
                 "Weapons",
                 "Armor",
                 "Map",
                 "World",
                 "Location",
                 "Mission",
                 "Bosses",
                 "Enemy",
                 "Friendly",
                 "Enemy"
              ],
              medium: [
                 "Team",
                 "Multiplayer",
                 "Online",
                 "Player",
                 "Cooperative",
                 "PvP (Player vs. Player)",
                 "PvE (Player vs. Environment)",
                 "PvP",
                 "Picture",
                 "Boss",
                 "Walkthrough",
                 "Tournament",
                 "Cheats",
                 "Hack",
                 "Ranking",
                 "Leaders",
                 "Gamer",
                 "Map",
                 "Dungeon",
                 "Secret",
                 "Final",
                 "Quests",
                 "Virtual Reality",
                 "Simulator",
                 "Platformer",
                 "RPG (Role Playing Game)",
                 "FPS (First Person Shooter)",
                 "CTS (Third Person Shooter)",
                 "Survival",
                 "Race",
                 "Sport",
                 "Arcade",
                 "Puzzle",
                 "Map",
                 "Cheats",
                 "Tournament",
                 "Rank",
                 "Virtual",
                 "Panel",
                 "Menu"
              ],
              hard: [
                 "Buildings",
                 "Zones",
                 "Cryptocurrency",
                 "Resources",
                 "Energy",
                 "Health",
                 "Money",
                 "Points",
                 "Unlock",
                 "Time Events",
                 "Keys",
                 "Models",
                 "Skins",
                 "Campaign",
                 "Multiplayer",
                 "Victories",
                 "Bouts",
                 "Achievements",
                 "Challenge",
                 "Fighters",
                 "Virtual",
                 "Mode",
                 "Task",
                 "Magic",
                 "Riddles",
                 "Heroes",
                 "Store",
                 "Buy",
                 "Sale",
                 "Market",
                 "Inventory",
                 "Cartridge",
                 "Keys",
                 "Upgrade",
                 "Final",
                 "Group",
                 "Store",
                 "Challenge",
                 "Reactions",
                 "Stream",
              ]),
        Words(id: 5,
              easy: [
                 "Brad Pitt",
                 "Jennifer Aniston",
                 "Tom Hanks",
                 "Angelina Jolie",
                 "Leonardo DiCaprio",
                 "Julia Roberts",
                 "Robert Downey Jr.",
                 "Meryl Streep",
                 "Will Smith",
                 "Sandra Bullock",
                 "Ryan Reynolds",
                 "Scarlett Johansson",
                 "Johnny Depp",
                 "Kate Winslet",
                 "Chris Hemsworth",
                 "Natalie Portman",
                 "Jason Momoa",
                 "Jennifer Lawrence",
                 "Charlize Theron",
                 "Matt Damon",
                 "Oscar Isaac",
                 "Emma Watson",
                 "Margot Robbie",
                 "Hugh Jackman",
                 "Cameron Diaz",
                 "Jodie Foster",
                 "Katy Perry",
                 "Taylor Swift",
                 "Ed Sheeran",
                 "Beyoncé",
                 "Lady Gaga",
                 "Justin Timberlake",
                 "Ariana Grande",
                 "Stevie Wonder",
                 "Bruce Willis",
                 "Jim Carrey",
                 "John Legend",
                 "Rihanna",
                 "Nicki Minaj",
                 "Chris Evans",
                 "Zendaya",
                 "Dwayne Johnson",
                 "Neil Patrick Harris",
                 "Jim Parsons",
                 "James Franco",
                 "Amy Adams",
                 "Adam Levine",
                 "Steve Carell",
                 "Helen Mirren",
                 "Joan Rivers",
                 "Benedict Cumberbatch",
                 "Gal Gadot",
                 "Richard Gere"
              ],
              medium: [
                 "Steven Spielberg",
                 "Hugh Laurie",
                 "Nicole Kidman",
                 "James Franco",
                 "Keira Knightley",
                 "Jake Gyllenhaal",
                 "Judi Dench",
                 "Ryan Gosling",
                 "Gwyneth Paltrow",
                 "Charlie Theron",
                 "Samuel L. Jackson",
                 "Penelope Cruz",
                 "Edward Norton",
                 "Cate Blanchett",
                 "Matt Damon",
                 "James McAvoy",
                 "Kate Beckinsale",
                 "Oscar Isaac",
                 "Emily Blunt",
                 "John Cena",
                 "Angelina Jolie",
                 "Julianne Moore",
                 "Tom Hiddleston",
                 "Rachel Weisz",
                 "Jude Law",
                 "Chris Pratt",
                 "Greta Gerwig",
                 "Nicolas Cage",
                 "John C. Reilly",
                 "Charlize Theron",
                 "Patti Smith",
                 "Sean Penn",
                 "Selma Hayek",
                 "Benicio Del Toro",
                 "Olivia Wilde",
                 "Eddie Redmayne",
                 "Chris Rock",
                 "John Kravitz",
                 "Reese Witherspoon",
                 "Jennifer Gardner",
                 "Josh Hutcherson",
                 "Ben Stiller",
                 "Zoe Saldana",
                 "Damian Bichir",
                 "Mila Kunis",
                 "Naomi Watts",
                 "Elissa Milano",
                 "Chris Evans",
                 "Daniel Radcliffe",
                 "Jodie Foster",
                 "Helen Hunt",
                 "Michelle Williams",
                 "Jack Nicholson"
              ],
              hard: [
                 "Alec Baldwin",
                 "Daniel Day-Lewis",
                 "Javier Bardem",
                 "Greta Gerwig",
                 "Rami Malek",
                 "Numphy Rapace",
                 "Christoph Waltz",
                 "Rachel Weisz",
                 "Edward Norton",
                 "Kristen Stewart",
                 "Benedict Cumberbatch",
                 "Marion Cotillard",
                 "Helen Mirren",
                 "Juliette Binoche",
                 "Sally Hawkins",
                 "Stephen Young",
                 "Mahershala Ali",
                 "Ruth Nega",
                 "Winona Ryder",
                 "Tilda Swinton",
                 "Simon Pegg",
                 "Naomi Watts",
                 "Oscar Isaac",
                 "Eddie Redmayne",
                 "Patricia Clarkson",
                 "Idris Elba",
                 "Judi Dench",
                 "Giovanni Ribisi",
                 "James McAvoy",
                 "Susan Sarandon",
                 "Jon Hamm",
                 "Olivia Colman",
                 "Kate Winslet",
                 "Hugo Weaving",
                 "Joan Allen",
                 "Jake Gyllenhaal",
                 "Martin Freeman",
                 "David Oyelowo",
                 "Elizabeth Debicki",
                 "Gwyneth Paltrow",
                 "Gennifer Lawrence",
                 "Greg Kinnear",
                 "Jeff Bridges",
                 "Toma Steers",
                 "Jason Statham",
                 "Anya Taylor-Joy",
                 "Ginnifer Gray",
                 "Christopher Lambert",
                 "Stephen Fry",
                 "Charlotte Rampling",
                 "Xavier Dolan",
                 "Robert Sheehan",
                 "Liev Schreiber"
              ]),
        Words(id: 6,
              easy: [
                 "Bread",
                 "Butter",
                 "Milk",
                 "Cheese",
                 "Egg",
                 "Meat",
                 "Fish",
                 "Chicken",
                 "Beef",
                 "Pork",
                 "Vegetables",
                 "Potatoes",
                 "Carrots",
                 "Tomato",
                 "Cucumber",
                 "Onion",
                 "Garlic",
                 "Pepper",
                 "Cabbage",
                 "Broccoli",
                 "Cauliflower",
                 "Lettuce",
                 "Apple",
                 "Banana",
                 "Orange",
                 "Pear",
                 "Kiwi",
                 "Grape",
                 "Watermelon",
                 "Melon",
                 "Berry",
                 "Honey",
                 "Yogurt",
                 "Sour cream",
                 "Porridge",
                 "Macaroni",
                 "Rice",
                 "Soup",
                 "Borscht",
                 "Dumplings",
                 "Vareniki",
                 "Pancakes",
                 "Pizza",
                 "Burgers",
                 "Hot dogs",
                 "Chips",
                 "Popcorn",
                 "Cupcake",
                 "Pie",
                 "Cookies",
                 "Chocolate",
                 "Candy",
                 "Ice cream",
                 "Compote",
                 "Tea",
                 "Coffee",
                 "Juice",
                 "Mineral water",
                 "Cottage cheese",
                 "Sausage",
                 "Sausages",
                 "Fish cutlets",
                 "Lasagna",
                 "Cutlets",
                 "Casserole",
                 "Omelette",
                 "Salad",
                 "Stew",
                 "Shashlyk",
                 "Buckwheat",
                 "Pancakes",
                 "Waffles",
                 "Sushi",
                 "Roll",
                 "Cake"
              ],
              medium: [
                 "Avocado",
                 "Salmon",
                 "Turkey",
                 "Squid",
                 "Tuna",
                 "Crab",
                 "Pate",
                 "Baked ham",
                 "Cheddar",
                 "Feta",
                 "Mascarpone",
                 "Tortilla",
                 "Burrito",
                 "Quesadilla",
                 "Ratatouille",
                 "Tapas",
                 "Guacamole",
                 "Chicken wings",
                 "Ribs",
                 "Croquettes",
                 "Quiche",
                 "Mashed Potato Soup",
                 "Cream soup",
                 "Salami",
                 "Pasta",
                 "Spaghetti",
                 "Risotto",
                 "Fettuccini",
                 "Lasagna",
                 "Chicken steak",
                 "Chili",
                 "Greek salad",
                 "Tabbouleh",
                 "Hummus",
                 "Lokshina",
                 "Dumplings",
                 "Vareniki",
                 "Pizza",
                 "Kebab",
                 "Shashlyk",
                 "Paprikash",
                 "Casserole",
                 "Stew",
                 "Kharcho soup",
                 "Buckwheat porridge",
                 "Couscous",
                 "Bulgur",
                 "Caprese",
                 "Sashimi",
                 "Sushi",
                 "Cheesecakes",
                 "Pudding",
                 "Mousse",
                 "Pancakes",
                 "Pancakes",
                 "Muffins",
                 "Cakes",
                 "Tart",
                 "Profiteroles",
                 "Macarons",
                 "Polenta",
                 "Falafel",
                 "Chicken cutlets",
                 "Vegetable stew",
                 "Frittata",
                 "Escalope",
                 "Burger",
                 "Dip",
                 "Herring under fur coat",
                 "Teppanyaki",
                 "Rolls",
                 "Yogurt Sauce",
                 "Fondue",
                 "Celery",
                 "Caramel"
              ],
              hard: [
                 "Duck confit",
                 "Chestnut cream",
                 "Beef carpaccio",
                 "Foie gras",
                 "Salmon Tartare",
                 "Ciabatta",
                 "Focaccia",
                 "Seafood Casserole",
                 "Vegetarian stew",
                 "Crème brûlée",
                 "Truffle oil",
                 "Spicy tagine",
                 "Arancini",
                 "Ratatouille",
                 "Cannelloni",
                 "Baba ganoush",
                 "Chicken liver pate",
                 "Calzone",
                 "Stuffed zucchini",
                 "Gazpacho",
                 "Miso soup",
                 "Lasagna Alfredo",
                 "Risotto with saffron",
                 "Chicken Paprikash",
                 "Burrata",
                 "Beef Stroganoff",
                 "Lamb kebab",
                 "Escargot",
                 "Crepes",
                 "Soufflé",
                 "Trout with almond sauce",
                 "Chia pudding",
                 "Salmon tartare",
                 "Fennel with olive oil",
                 "Agnus a la grill",
                 "Caprese",
                 "Grilled sepia",
                 "Lamb Kebab",
                 "Tom Yum",
                 "Strudel",
                 "Stuffed peppers",
                 "Korean cucumbers",
                 "Ricotta pie",
                 "Brioche",
                 "Stuffed mushrooms",
                 "Onion soup",
                 "Truffle risotto",
                 "Greek moussaka",
                 "Ceviche",
                 "Mussels in white wine",
                 "Cherry pie",
                 "Tortilla de patatas",
                 "Caviar pancakes",
                 "Tiramisu",
                 "Flanders steak",
                 "Champagne sauce",
                 "Sesame oil",
                 "Beef Tartare",
                 "Suluguni",
                 "Agnestones",
                 "Chocolate fondant",
                 "Quinoa salad",
                 "Baked eggplants",
                 "Enchiladas",
                 "Funchoza",
                 "Seaweed soup",
                 "Shrimp teriyaki",
                 "Kulebyaka",
                 "Cumin",
                 "Indian curry",
                 "Seafood salad",
                 "Cake with mascarpone cream",
                 "Lasagna with mushrooms",
                 "White Mushroom Soup",
                 "Avocado and mango salad"
              ]),
        Words(id: 7,
              easy: [
                 "Forest",
                 "Mountain",
                 "River",
                 "Lake",
                 "Sea",
                 "Ocean",
                 "Beach",
                 "Sun",
                 "Moon",
                 "Star",
                 "Thunderstorm",
                 "Rain",
                 "Snow",
                 "Fog",
                 "Wind",
                 "Grass",
                 "Flower",
                 "Tree",
                 "Bush",
                 "Leaf",
                 "Root",
                 "Bird",
                 "Beetle",
                 "Butterfly",
                 "Gnat",
                 "Bear",
                 "Wolf",
                 "Fox",
                 "Hare",
                 "Deer",
                 "Horse",
                 "Dog",
                 "Cat",
                 "Fish",
                 "Lightning",
                 "Wave",
                 "Sand",
                 "Pebble",
                 "Stone",
                 "Rock"
              ],
              medium: [
                 "Cave",
                 "Spring",
                 "Spring",
                 "Pond",
                 "Salt Lake",
                 "Meadow",
                 "Valley",
                 "Glade",
                 "Birdhouse",
                 "Nest",
                 "Barrow",
                 "Path",
                 "Bridge",
                 "Waterfall",
                 "Stream",
                 "Garden",
                 "Orchard",
                 "Front garden",
                 "Greenhouse",
                 "Noise",
                 "Tranquility",
                 "Landscape",
                 "Nature",
                 "Ecosystem",
                 "Climate",
                 "Temperature",
                 "Humidity",
                 "Trees",
                 "Shrub",
                 "Shoemaker",
                 "Shallow",
                 "Shore",
                 "Flood",
                 "Forest glade",
                 "Moss",
                 "Mushrooms",
                 "Berries",
                 "Nuts",
                 "Dewberry",
                 "Melissa"
              ],
              hard: [
                 "Rosehip",
                 "Lavender",
                 "Petunia",
                 "Chamomile",
                 "Cornflower",
                 "Tulip",
                 "Iris",
                 "Gladiolus",
                 "Kalina",
                 "Rowan",
                 "Dandelion",
                 "Clover",
                 "Melissa",
                 "Camellia",
                 "Jasmine",
                 "Fern",
                 "Reseda",
                 "Cherada",
                 "Nettle",
                 "Laurel leaf",
                 "Cherada",
                 "Laurel",
                 "Pistachio",
                 "Orchid",
                 "Amaranth",
                 "Lotus",
                 "Calendula",
                 "Lily of the valley",
                 "Sparrowberry",
                 "Geranium",
                 "Fuchsia",
                 "Edelweiss",
                 "Peonies",
                 "Lily",
                 "Saffron",
                 "Elderberry",
                 "Lilac",
                 "Calypso",
                 "Pastel",
                 "Poplar"
              ]),
        Words(id: 8,
              easy: [
                 "Automobile",
                 "Train",
                 "Airplane",
                 "Bus",
                 "Trolleybus",
                 "Streetcar",
                 "Bicycle",
                 "Motorcycle",
                 "Ship",
                 "Boat",
                 "Yacht",
                 "Submarine",
                 "High-speed train",
                 "Subway",
                 "Scooter",
                 "Rickshaw",
                 "Truck",
                 "Car",
                 "Convertible",
                 "SUV",
                 "Van",
                 "Sedan",
                 "Crossover",
                 "Minibus",
                 "Electric scooter",
                 "Racing car",
                 "Tank",
                 "Scooter",
                 "Transformer",
                 "Minibus",
                 "Platform",
                 "Railroad train",
                 "Railroad train",
                 "Hydrocycle"
              ],
              medium: [
                 "Tourist bus",
                 "Passenger airplane",
                 "Biplane",
                 "Helicopter",
                 "Agricultural transport",
                 "Freight train",
                 "Subway",
                 "Aeroexpress",
                 "Modular train",
                 "Shuttle",
                 "Sea tugboat",
                 "Tourist vessel",
                 "River transport",
                 "Passenger boat",
                 "Shuttle",
                 "Ultralighter",
                 "Bomber",
                 "Jeep",
                 "Warp",
                 "Stunt Car",
                 "Jet Engine",
                 "Road bike",
                 "Racing Motorcycle",
                 "Cargo van",
                 "Air Mail",
                 "Airplane",
                 "Speedboat",
                 "Trailer",
                 "Electric car",
                 "Trolleybus route",
                 "Agricultural combine",
                 "Ball bearing",
                 "Elevator",
                 "Skateboard"
              ],
              hard: [
                 "Passenger transportation",
                 "Passenger boat",
                 "Balloon",
                 "Trolleybus station",
                 "Metroexpress",
                 "Tandem",
                 "Jet airplane",
                 "Shipping container",
                 "Ferry",
                 "Flight Controller",
                 "Cargo ship",
                 "Storm boat",
                 "Landing gear",
                 "Rail vehicle",
                 "Motorcycle with sidecar",
                 "Sky transport",
                 "Rolling Car",
                 "Cargo van",
                 "Road train",
                 "Tanker",
                 "Electric bus",
                 "Speedboat",
                 "Tugboat",
                 "Underground subway",
                 "Savelievsky train",
                 "Truck Crane",
                 "Manipulator crane",
                 "Suburban train",
                 "Light rail transportation",
                 "River steamer",
                 "Two-seater airplane",
                 "Recreational boat",
                 "Bus station",
                 "Mechanical transportation"
              ]),
        Words(id: 9, easy: [], medium: [], hard: [])
    ]
}
